
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 27 14:05:42 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface LibrarySym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int CLASSIDENT = 45;
  public static final int LCBR = 21;
  public static final int STRING_LITERAL = 47;
  public static final int LTE = 27;
  public static final int UMINUS = 48;
  public static final int INTEGER = 49;
  public static final int SEMI = 38;
  public static final int CONTINUE = 7;
  public static final int INT = 17;
  public static final int LIBRARY = 46;
  public static final int MINUS = 28;
  public static final int STATIC = 39;
  public static final int LT = 26;
  public static final int LP = 20;
  public static final int COMMA = 6;
  public static final int CLASS = 5;
  public static final int RP = 37;
  public static final int PLUS = 33;
  public static final int MULTIPLY = 30;
  public static final int QUOTE = 52;
  public static final int ASSIGN = 2;
  public static final int IF = 16;
  public static final int THIS = 41;
  public static final int ID = 51;
  public static final int DOT = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 36;
  public static final int RCBR = 35;
  public static final int LB = 19;
  public static final int LAND = 18;
  public static final int EQUAL = 10;
  public static final int TRUE = 42;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int RB = 34;
  public static final int LOR = 25;
  public static final int NULL = 32;
  public static final int MOD = 29;
  public static final int BREAK = 4;
  public static final int VOID = 43;
  public static final int GTE = 15;
  public static final int ELSE = 12;
  public static final int WHILE = 44;
  public static final int NEQUAL = 31;
  public static final int CLASS_ID = 50;
  public static final int EXTENDS = 11;
  public static final int STRING = 40;
  public static final int LNEG = 24;
  public static final int FALSE = 13;
  public static final int GT = 14;
  public static final int LENGTH = 22;
}

