
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 27 14:05:42 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated class containing symbol constants. */
public class SlpSym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 35;
  public static final int LTE = 13;
  public static final int UMINUS = 20;
  public static final int INTEGER = 16;
  public static final int SEMI = 8;
  public static final int CONTINUE = 26;
  public static final int INT = 33;
  public static final int MINUS = 3;
  public static final int STATIC = 44;
  public static final int LT = 11;
  public static final int LP = 6;
  public static final int COMMA = 25;
  public static final int CLASS = 24;
  public static final int RP = 7;
  public static final int PLUS = 2;
  public static final int MULTIPLY = 4;
  public static final int ASSIGN = 9;
  public static final int QUOTE = 19;
  public static final int IF = 32;
  public static final int THIS = 46;
  public static final int DOT = 27;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int RETURN = 43;
  public static final int RCBR = 42;
  public static final int LB = 34;
  public static final int LAND = 14;
  public static final int EQUAL = 28;
  public static final int TRUE = 47;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int RB = 41;
  public static final int LOR = 15;
  public static final int NULL = 40;
  public static final int MOD = 21;
  public static final int BREAK = 23;
  public static final int VOID = 48;
  public static final int GTE = 12;
  public static final int ELSE = 30;
  public static final int WHILE = 49;
  public static final int NEQUAL = 39;
  public static final int CLASS_ID = 18;
  public static final int EXTENDS = 29;
  public static final int STRING = 45;
  public static final int LNEG = 38;
  public static final int FALSE = 31;
  public static final int GT = 10;
  public static final int LENGTH = 36;
}

